# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.currentTrial = QtWidgets.QLineEdit(self.centralwidget)
        self.currentTrial.setEnabled(True)
        self.currentTrial.setMaximumSize(QtCore.QSize(80, 16777215))
        self.currentTrial.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"border-color: rgb(0, 0, 0);")
        self.currentTrial.setReadOnly(True)
        self.currentTrial.setObjectName("currentTrial")
        self.horizontalLayout.addWidget(self.currentTrial)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.usersCounter = QtWidgets.QLineEdit(self.centralwidget)
        self.usersCounter.setMaximumSize(QtCore.QSize(100, 16777215))
        self.usersCounter.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"border-color: rgb(0, 0, 0);")
        self.usersCounter.setReadOnly(True)
        self.usersCounter.setObjectName("usersCounter")
        self.horizontalLayout.addWidget(self.usersCounter)
        self.nextTrialButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextTrialButton.setObjectName("nextTrialButton")
        self.horizontalLayout.addWidget(self.nextTrialButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.endButton = QtWidgets.QPushButton(self.centralwidget)
        self.endButton.setObjectName("endButton")
        self.horizontalLayout.addWidget(self.endButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.description = QtWidgets.QLineEdit(self.centralwidget)
        self.description.setMinimumSize(QtCore.QSize(300, 0))
        self.description.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"border-color: rgb(0, 0, 0);")
        self.description.setReadOnly(True)
        self.description.setObjectName("description")
        self.horizontalLayout_2.addWidget(self.description)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.average = QtWidgets.QLineEdit(self.centralwidget)
        self.average.setMaximumSize(QtCore.QSize(150, 16777215))
        self.average.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"border-color: rgb(0, 0, 0);")
        self.average.setReadOnly(True)
        self.average.setObjectName("average")
        self.horizontalLayout_2.addWidget(self.average)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.displayPreview = QtWidgets.QLineEdit(self.centralwidget)
        self.displayPreview.setMinimumSize(QtCore.QSize(300, 0))
        self.displayPreview.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"border-color: rgb(0, 0, 0);")
        self.displayPreview.setReadOnly(True)
        self.displayPreview.setObjectName("displayPreview")
        self.horizontalLayout_3.addWidget(self.displayPreview)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.retryTrial = QtWidgets.QPushButton(self.groupBox)
        self.retryTrial.setObjectName("retryTrial")
        self.verticalLayout.addWidget(self.retryTrial)
        self.deselectRow = QtWidgets.QPushButton(self.groupBox)
        self.deselectRow.setObjectName("deselectRow")
        self.verticalLayout.addWidget(self.deselectRow)
        spacerItem1 = QtWidgets.QSpacerItem(20, 64, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 63, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 6, 0, 1, 1)
        self.userNumber = QtWidgets.QLineEdit(self.groupBox)
        self.userNumber.setMaximumSize(QtCore.QSize(150, 16777215))
        self.userNumber.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.userNumber.setReadOnly(True)
        self.userNumber.setObjectName("userNumber")
        self.gridLayout.addWidget(self.userNumber, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.userTrialAverage = QtWidgets.QLineEdit(self.groupBox)
        self.userTrialAverage.setMaximumSize(QtCore.QSize(150, 16777215))
        self.userTrialAverage.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.userTrialAverage.setReadOnly(True)
        self.userTrialAverage.setObjectName("userTrialAverage")
        self.gridLayout.addWidget(self.userTrialAverage, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.userAverageAll = QtWidgets.QLineEdit(self.groupBox)
        self.userAverageAll.setMaximumSize(QtCore.QSize(150, 16777215))
        self.userAverageAll.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.userAverageAll.setReadOnly(True)
        self.userAverageAll.setObjectName("userAverageAll")
        self.gridLayout.addWidget(self.userAverageAll, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.userAverageAllAndBonus = QtWidgets.QLineEdit(self.groupBox)
        self.userAverageAllAndBonus.setMaximumSize(QtCore.QSize(150, 16777215))
        self.userAverageAllAndBonus.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.userAverageAllAndBonus.setReadOnly(True)
        self.userAverageAllAndBonus.setObjectName("userAverageAllAndBonus")
        self.gridLayout.addWidget(self.userAverageAllAndBonus, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.userTrial = QtWidgets.QLineEdit(self.groupBox)
        self.userTrial.setMaximumSize(QtCore.QSize(150, 16777215))
        self.userTrial.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.userTrial.setReadOnly(True)
        self.userTrial.setObjectName("userTrial")
        self.gridLayout.addWidget(self.userTrial, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.userSum = QtWidgets.QLineEdit(self.groupBox)
        self.userSum.setMaximumSize(QtCore.QSize(150, 16777215))
        self.userSum.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.userSum.setReadOnly(True)
        self.userSum.setObjectName("userSum")
        self.gridLayout.addWidget(self.userSum, 6, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.sendToDisplay = QtWidgets.QPushButton(self.groupBox)
        self.sendToDisplay.setObjectName("sendToDisplay")
        self.verticalLayout.addWidget(self.sendToDisplay)
        self.horizontalLayout_5.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuGare = QtWidgets.QMenu(self.menubar)
        self.menuGare.setObjectName("menuGare")
        self.menuImpostazioni = QtWidgets.QMenu(self.menubar)
        self.menuImpostazioni.setObjectName("menuImpostazioni")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNuova_gara = QtWidgets.QAction(MainWindow)
        self.actionNuova_gara.setObjectName("actionNuova_gara")
        self.actionCarica = QtWidgets.QAction(MainWindow)
        self.actionCarica.setObjectName("actionCarica")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionConfigura = QtWidgets.QAction(MainWindow)
        self.actionConfigura.setObjectName("actionConfigura")
        self.actionGenera_rapporto = QtWidgets.QAction(MainWindow)
        self.actionGenera_rapporto.setObjectName("actionGenera_rapporto")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuGare.addAction(self.actionNuova_gara)
        self.menuGare.addAction(self.actionCarica)
        self.menuGare.addSeparator()
        self.menuGare.addAction(self.actionSaveAs)
        self.menuGare.addSeparator()
        self.menuGare.addAction(self.actionGenera_rapporto)
        self.menuImpostazioni.addAction(self.actionConfigura)
        self.menubar.addAction(self.menuGare.menuAction())
        self.menubar.addAction(self.menuImpostazioni.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Giudice di gara v1.0"))
        self.label.setText(_translate("MainWindow", "Prova corrente"))
        self.label_3.setText(_translate("MainWindow", "Pettorine giudicate"))
        self.nextTrialButton.setText(_translate("MainWindow", "Fine prova"))
        self.startButton.setText(_translate("MainWindow", "Avvia gara!"))
        self.endButton.setText(_translate("MainWindow", "Fine gara!"))
        self.label_2.setText(_translate("MainWindow", "Descrizione"))
        self.label_9.setText(_translate("MainWindow", "Media"))
        self.label_5.setText(_translate("MainWindow", "Testo sul display"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.groupBox.setTitle(_translate("MainWindow", "Opzioni pettorina selezionata"))
        self.retryTrial.setToolTip(_translate("MainWindow", "Vengono resettati i giudizi per la pettorina selezionata nella prova selezionata"))
        self.retryTrial.setText(_translate("MainWindow", "Riprova..."))
        self.deselectRow.setText(_translate("MainWindow", "Deseleziona"))
        self.label_11.setText(_translate("MainWindow", "Somma"))
        self.label_6.setText(_translate("MainWindow", "Punteggio\n"
"prova"))
        self.label_7.setText(_translate("MainWindow", "Media\n"
"punteggio"))
        self.label_8.setText(_translate("MainWindow", "Punteggio\n"
"con crediti"))
        self.label_4.setText(_translate("MainWindow", "Pettorina"))
        self.label_10.setText(_translate("MainWindow", "Prova"))
        self.sendToDisplay.setText(_translate("MainWindow", "Mostra sul display"))
        self.menuGare.setTitle(_translate("MainWindow", "Files"))
        self.menuImpostazioni.setTitle(_translate("MainWindow", "Gara"))
        self.actionNuova_gara.setText(_translate("MainWindow", "Nuova gara..."))
        self.actionCarica.setText(_translate("MainWindow", "Apri gara..."))
        self.actionSaveAs.setText(_translate("MainWindow", "Crea una copia..."))
        self.actionConfigura.setText(_translate("MainWindow", "Configura pettorine..."))
        self.actionGenera_rapporto.setText(_translate("MainWindow", "Genera rapporto..."))
        self.actionSave.setText(_translate("MainWindow", "Salva"))

