# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newgara.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 264)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.description = QtWidgets.QLineEdit(Dialog)
        self.description.setObjectName("description")
        self.horizontalLayout.addWidget(self.description)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        self.dateEdit.setLocale(QtCore.QLocale(QtCore.QLocale.Italian, QtCore.QLocale.Italy))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_3.addWidget(self.dateEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.numeroGiudici = QtWidgets.QComboBox(Dialog)
        self.numeroGiudici.setObjectName("numeroGiudici")
        self.numeroGiudici.addItem("")
        self.numeroGiudici.addItem("")
        self.numeroGiudici.addItem("")
        self.numeroGiudici.addItem("")
        self.numeroGiudici.addItem("")
        self.numeroGiudici.addItem("")
        self.horizontalLayout_2.addWidget(self.numeroGiudici)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.prove = QtWidgets.QComboBox(Dialog)
        self.prove.setObjectName("prove")
        self.prove.addItem("")
        self.prove.addItem("")
        self.prove.addItem("")
        self.prove.addItem("")
        self.prove.addItem("")
        self.horizontalLayout_4.addWidget(self.prove)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.atleti = QtWidgets.QLineEdit(Dialog)
        self.atleti.setObjectName("atleti")
        self.horizontalLayout_5.addWidget(self.atleti)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Nuova gara"))
        self.label.setText(_translate("Dialog", "Descrizione"))
        self.label_3.setText(_translate("Dialog", "Data riferimento"))
        self.label_2.setText(_translate("Dialog", "Numero giudici"))
        self.numeroGiudici.setItemText(0, _translate("Dialog", "1"))
        self.numeroGiudici.setItemText(1, _translate("Dialog", "2"))
        self.numeroGiudici.setItemText(2, _translate("Dialog", "3"))
        self.numeroGiudici.setItemText(3, _translate("Dialog", "4"))
        self.numeroGiudici.setItemText(4, _translate("Dialog", "5"))
        self.numeroGiudici.setItemText(5, _translate("Dialog", "6"))
        self.label_4.setText(_translate("Dialog", "Numero prove"))
        self.prove.setItemText(0, _translate("Dialog", "1"))
        self.prove.setItemText(1, _translate("Dialog", "2"))
        self.prove.setItemText(2, _translate("Dialog", "3"))
        self.prove.setItemText(3, _translate("Dialog", "4"))
        self.prove.setItemText(4, _translate("Dialog", "5"))
        self.label_5.setText(_translate("Dialog", "Numero atleti"))
        self.atleti.setText(_translate("Dialog", "100"))

