# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newgara.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(594, 404)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.description = QtWidgets.QLineEdit(self.groupBox)
        self.description.setObjectName("description")
        self.horizontalLayout.addWidget(self.description)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setLocale(QtCore.QLocale(QtCore.QLocale.Italian, QtCore.QLocale.Italy))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_3.addWidget(self.dateEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.numeroGiudici = QtWidgets.QComboBox(self.groupBox)
        self.numeroGiudici.setObjectName("numeroGiudici")
        self.numeroGiudici.addItem("")
        self.numeroGiudici.addItem("")
        self.numeroGiudici.addItem("")
        self.numeroGiudici.addItem("")
        self.numeroGiudici.addItem("")
        self.numeroGiudici.addItem("")
        self.horizontalLayout_2.addWidget(self.numeroGiudici)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.prove = QtWidgets.QComboBox(self.groupBox)
        self.prove.setObjectName("prove")
        self.prove.addItem("")
        self.prove.addItem("")
        self.prove.addItem("")
        self.prove.addItem("")
        self.prove.addItem("")
        self.prove.addItem("")
        self.prove.addItem("")
        self.prove.addItem("")
        self.prove.addItem("")
        self.prove.addItem("")
        self.horizontalLayout_4.addWidget(self.prove)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.atleti = QtWidgets.QLineEdit(self.groupBox)
        self.atleti.setObjectName("atleti")
        self.horizontalLayout_5.addWidget(self.atleti)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.votoMassimo = QtWidgets.QLineEdit(self.groupBox)
        self.votoMassimo.setObjectName("votoMassimo")
        self.horizontalLayout_7.addWidget(self.votoMassimo)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_6.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_6.addWidget(self.radioButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Nuovo esame"))
        self.groupBox.setTitle(_translate("Dialog", "Impostazioni"))
        self.label.setText(_translate("Dialog", "Descrizione"))
        self.label_3.setText(_translate("Dialog", "Data riferimento"))
        self.label_2.setText(_translate("Dialog", "Numero giudici"))
        self.numeroGiudici.setItemText(0, _translate("Dialog", "1"))
        self.numeroGiudici.setItemText(1, _translate("Dialog", "2"))
        self.numeroGiudici.setItemText(2, _translate("Dialog", "3"))
        self.numeroGiudici.setItemText(3, _translate("Dialog", "4"))
        self.numeroGiudici.setItemText(4, _translate("Dialog", "5"))
        self.numeroGiudici.setItemText(5, _translate("Dialog", "6"))
        self.label_4.setText(_translate("Dialog", "Numero prove"))
        self.prove.setItemText(0, _translate("Dialog", "1"))
        self.prove.setItemText(1, _translate("Dialog", "2"))
        self.prove.setItemText(2, _translate("Dialog", "3"))
        self.prove.setItemText(3, _translate("Dialog", "4"))
        self.prove.setItemText(4, _translate("Dialog", "5"))
        self.prove.setItemText(5, _translate("Dialog", "6"))
        self.prove.setItemText(6, _translate("Dialog", "7"))
        self.prove.setItemText(7, _translate("Dialog", "8"))
        self.prove.setItemText(8, _translate("Dialog", "9"))
        self.prove.setItemText(9, _translate("Dialog", "10"))
        self.label_5.setText(_translate("Dialog", "Numero concorrenti"))
        self.atleti.setText(_translate("Dialog", "100"))
        self.label_6.setText(_translate("Dialog", "Voto massimo"))
        self.votoMassimo.setText(_translate("Dialog", "10.0"))
        self.radioButton.setText(_translate("Dialog", "Media aritmetica"))
        self.radioButton_2.setText(_translate("Dialog", "Media mediata (tolto min e max)"))

